name: Release Workflow

on:
  push:
    branches:
      - main  # or any other branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip files
      run: zip rewrite.zip background.js selection.js selection.css manifest.json

    - name: Generate Tag
      uses: anothrNick/github-tag-action@1.30.0
      id: generate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "rewrite.zip"
        tag: ${{ steps.generate.outputs.new_tag }}
        commit: ${{ github.ref }}
